#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
   for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
   done
   unset f
fi

xset s off         # don't activate screensaver
xset -dpms         # disable DPMS (Energy Star) features.
xset s noblank     # don't blank the video device

export DISPLAY=:0
xscreensaver -no-splash &
sed -i 's/"exited_cleanly": false/"exited_cleanly": true/' ~/.config/chromium/Default/Preferences
feh /etc/splash.jpg &
exec chromium-browser --incognito --kiosk http://127.0.0.1/
